version: '3.7'
services:
  pengchsky-web-1:
    container_name: pengchsky-web-1
    image: ccr.ccs.tencentyun.com/sanliankeji/pengchsky-web:DOCKER_IMAGE_TAG
    restart: always
    ports:
      - "6343:80"
    networks:
      - hostnet
networks:
  hostnet:
    external: true
    name: overall_communication
