version: '3.7'
services:
  pengchsky-web:
    container_name: pengchsky-web
    image: ccr.ccs.tencentyun.com/sanliankeji/pengchsky-web:test
    restart: always
    ports:
      - "6343:80"
    networks:
      - hostnet
networks:
  hostnet:
    external: true
    name: overall_communication
